[project]
name = "upload-assistant"
version = "7.0.2"
requires-python = ">=3.9"
description = "A simple tool to take the work out of uploading."
readme = "README.md"
dependencies = [
    "aiofiles==25.1.0",
    "aiohttp==3.13.3",
    "anitopy==2.1.1",
    "argon2-cffi==25.1.0",
    "babel==2.17.0",
    "bbcode==1.1.0",
    "beautifulsoup4==4.14.2",
    "bencode-py==4.0.0",
    "cachelib==0.13.0",
    "cli-ui==0.19.0",
    "click==8.1.8",
    "cloudscraper==1.2.71",
    "cryptography==46.0.3",
    "defusedxml==0.7.1",
    "deluge-client==1.10.2",
    "discord-py==2.6.4",
    "ffmpeg-python==0.2.0",
    "flask==3.1.2",
    "flask-cors==6.0.2",
    "flask-limiter==3.11.0",
    "flask-session==0.8.0",
    "guessit==3.8.0",
    "httpx==0.28.1",
    "jinja2==3.1.6",
    "keyring==25.6.0",
    "langcodes==3.5.1",
    "language-data==1.4.0",
    "lxml==6.0.2",
    "nest-asyncio==1.6.0",
    "packaging>=21,<25",
    "pillow==11.3.0",
    "psutil==7.1.3",
    "pycountry==24.6.1",
    "pyimgbox==1.0.7",
    "pymediainfo==7.0.1",
    "pyotp==2.9.0",
    "qbittorrent-api==2025.7.0",
    "regex==2025.11.3",
    "requests==2.32.5",
    "rich==13.9.4",
    "setuptools==80.9.0",
    "tmdbsimple==2.9.1",
    "torf==4.3.0",
    "tqdm==4.67.1",
    "transmission-rpc==7.0.11",
    "tvdb-v4-official==1.1.0",
    "unidecode==1.4.0",
    "urllib3==2.6.3",
    "waitress==3.0.2",
]


[tool.ruff]
line-length = 176
target-version = "py39"
exclude = ["tests", "data"]

[tool.ruff.lint]
select = [
  # Core correctness
  "E",
  "F",
  "W",
  "B",

  # Imports & modernization
  "I",
  "UP",

  # Code quality
  "C4",
  "SIM",
  "PERF",
  "ARG",

  # Dates & time
  "DTZ",

  # Async (if applicable)
  "ASYNC",
]
ignore = ["E501", "UP045"]

[tool.ruff.lint.isort]
known-first-party = ["cogs", "data", "src", "web_ui"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownMemberType = true
reportUnknownVariableType = true
exclude = ["data"]
